[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
via_ir = false
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]




[rpc_endpoints]
bsc = "https://bsc-dataseed1.binance.org"
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545"
blockdag_testnet = "https://rpc.awakening.bdagscan.com"  # BlockDag testnet RPC

[etherscan]
bsc = { key = "${BSCSCAN_API_KEY}" }
bsc_testnet = { key = "${BSCSCAN_API_KEY}" }
